const pluralize = require('pluralize');

const maxAmount = 20;

module.exports = getRandomFood;

function getRandomFood(){
	const getSpecial = Math.random() < 0.01;
	let amount = Math.floor(maxAmount * (Math.random() + Math.random())) + 1;
	
	if(getSpecial){
		const foodIndex = Math.floor(Math.random() * specialFood.length);
		const makePlural = amount == 1;
		const foodItem = makePlural ? pluralize(specialFood[foodIndex]) : specialFood[foodIndex];
		
		const singleStorage = pluralStorageItems[Math.floor(Math.random()*singleStorageItems.length)];
		const pluralStorage = singleStorageItems[Math.floor(Math.random()*pluralStorageItems.length)];
		const storage = makePlural ? pluralStorage : singleStorage;
		
		return storage.replace(/\{0\}/g, foodItem);
	} else {
		const allFood = foodItems.concat(canBePlural);
		const totalFoodItems = allFood.length;
		const foodIndex = Math.floor(Math.random() * allFood.length);
		const makePlural = amount == 1 ? false : foodIndex > foodItems.length;
		const foodItem = makePlural ? pluralize(allFood[foodIndex]) : allFood[foodIndex];
		
		const singleStorage = singleStorageItems[Math.floor(Math.random()*singleStorageItems.length)];
		const pluralStorage = pluralStorageItems[Math.floor(Math.random()*pluralStorageItems.length)];
		const storage = makePlural ? pluralStorage : singleStorage;
		
		return storage.replace(/\{0\}/g, foodItem);
	}
}

const singleStorageItems = [
	'1 {0}',
	'one {0}',
	'a single {0}',
	'a single, large, {0}',
	'a single, small, {0}',
	'the tiniest {0} that anyone has seen',
	'the largest {0} that anyone has seen',
	'one {0} on a plate far too big',
	'one {0} on a plate far too small',
	'one {0} in a glass far too big',
	'one {0} in a glass far too small',
	'one {0} in a bowl far too big',
	'one {0} in a bowl far too small',

	'a {0} in a broken bowl',
	'a {0} on a broken plate',
	'a {0} in a broken glass',
	'a {0} on a stick'
]
const pluralStorageItems = [
	'a barrel full of {0}',
	'a plate full of {0}',
	'a bowl full of {0}',
	'a cup full of {0}',
	'a house full of {0}',
	'a bank full of {0}',
	'a ship full of {0}',
	'a planet full of {0}',
	'a solar system full of {0}',
	'a desk full of {0}',
	'a box full of {0}',
	'a computer full of {0}',
	'a mountain full of {0}',
	'a bag full of {0}',
	'a backpack full of {0}',
	'a water bottle full of {0}',
	'Huston full of {0}',
	'Seattle full of {0}',
	'a gas station full of {0}',
	'a supermarket full of {0}',
	'a painting about {0}',
	'a basket full of {0}',
	'a picnic full of {0}',
	'a bed full of {0}',
	'a drawer full of {0}',
	'a poof full of {0}',
	'a door full of {0}',
	'a data set full of {0}',
	'a song about {0}',
	'a beehive full of {0}',
	'a book about {0}'
]

const specialFood = [
	'leaf',
	'chirry',
	'chirrberry',
	'diet double dew',
	'garfield\'s lasagna',
	'fake milk',
	'rock',
	'olive ciabatta bread',
	'chicken tendy'
];

const canBePlural = [
	'apple',
	'banana',
	'berry',
	'grape',
	'lemon',
	'lime',
	'melon',
	'nectarine',
	'orange',
	'peach',
	'pear',
	'plumb',
	'strawberry',
	'watermelon',
	'cabbage',
	'carrot',
	'cauliflower',
	'mushroom',
	'onion',
	'pepper',
	'potato',
	'tomato',
	'zucchini',
	'cherry',
	'pineapple',
	'baked bean',
	'butter bean',
	'green bean',
	'kidney bean',
	'pinto bean',
	'string bean',
	'french fry',
	'pea',
	'pizza',
	'tater tot',
	'beef steak',
	'boneless chicken breast',
	'chicken leg',
	'whole chicken',
	'boneless chicken wing',
	'chicken wing',
	'ham slice',
	'turkey slice',
	'bacon slice',
	'roast beef',
	'pork chop',
	'pork sausage',
	'crab',
	'scallop',
	'bacon wrapped scallop',
	'tuna melt',
	'grilled cheese',
	'candy',
	'cookie',
	'cracker',
	'nut',
	'potato chip',
	'crisp',
	'pretzel',
	'rasin',
	'biscuit',
	'bread',
	'white bread',
	'wheat bread',
	'rye bread',
	'rasin bread',
	'pumpernickle bread',
	'french bread',
	'bun',
	'wheat roll',
	'white roll',
	'rye roll',
	'bagel',
	'everything bagel',
	'poppy seed bagel',
	'rasin bagel',
	'egg',
	'refried bean',
	'taco',
	'chicken taco',
	'lamb taco',
	'beef taco',
	'corn tortilla',
	'pancake',
	'brownie',
	'chocolate'
]

const foodItems = [
	'beef chilli',
	'cereal',
	'apple juice',
	'grape juice',
	'orange juice',
	'celery',
	'corn',
	'garlic',
	'lettuce',
	'squash', 
	'ice cream',
	'ground beef',
	'roast pork',
	'fish',
	'tuna',
	'pike',
	'trout',
	'soup',
	'stew',
	'chowder',
	'popcorn',
	'chicken noodle soup',
	'cream of celery soup',
	'cream of chicken soup',
	'cream of mushroom soup',
	'tomato soup',
	'vegetable soup',
	'beef soup',
	'chicken soup',
	'coffe',
	'iced coffe',
	'2% milk',
	'skim milk',
	'1% milk',
	'1.5% milk',
	'3% milk',
	'whole milk',
	'almond milk',
	'soy milk',
	'soft drink',
	'Dr. Pepper',
	'Mountain Dew',
	'Coca-Cola',
	'Fanta',
	'7-up',
	'Sprite',
	'Pepsi',
	'Snapple',
	'Gatorade',
	'Monster',
	'Rockstar',
	'Sports Drink',
	'black tea',
	'green tea',
	'oolong tea',
	'herbal tea',
	'white tea',
	'yellow tea',
	'chamomile tea',
	'water',
	'cheese',
	'mozzarella cheese',
	'cheddar cheese',
	'sharp cheddar cheese',
	'extra sharp cheddar cheese',
	'brie cheese',
	'feta cheese',
	'gorgonzola cheese',
	'cottage cheese',
	'cream cheese',
	'sliced cheese',
	'yogurt',
	'sour cream',
	'spaghetti',
	'pesto spaghetti',
	'buttered spaghetti',
	'red sauce spaghetti',
	'angel hair spaghetti',
	'macaroni',
	'macaroni soup',
	'macaroni and cheese',
	'lasagna',
	'beef lasagna',
	'cheese lasagna',
	'vegetable lasagna',
	'spanish rice',
	'lucky charms',
	'cinnamon toast crunch',
	'chocolate milk',
	'strawberry milk',
	'blueberry milk',
	'banana milk',
	'jello',
	'oatmeal',
	'rice',
	'brown rice',
	'white rice'
]